# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  docker-builder:
    environment:
      IMAGE_NAME: ghcr.io/nltimv/karma-chameleon
      CHART_PATH: ./charts/karma-chameleon
      GHCR_USERNAME: nltimv
    docker:
      - image: docker:20
    resource_class: small
  helm-builder:
    environment:
      APP_NAME: karma-chameleon
      CHART_NAME: ghcr.io/nltimv/karma-chameleon-helm
      CHART_DEV_NAME: ghcr.io/nltimv/karma-chameleon-helm-dev
      CHART_PATH: ./charts/karma-chameleon
      GHCR_USERNAME: nltimv
    docker:
      - image: cimg/deploy:2023.09

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-docker-dev:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t build:latest .
      - run:
          name: Publish Docker Image to GitHub Container Registry
          command: |
            export REVISION=$(echo "<< pipeline.git.revision >>" | awk '{print substr($0,0,7)}')
            export VERSION="0.0.0.<< pipeline.number >>-dev-$REVISION"
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker tag build:latest $IMAGE_NAME:canary
            docker push $IMAGE_NAME:canary
            docker tag $IMAGE_NAME:canary $IMAGE_NAME:$VERSION
            docker push $IMAGE_NAME:$VERSION
  build-docker-release:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t build:latest .
      - run:
          name: Publish Docker Image to GitHub Container Registry
          command: |
            export NUMBER=$(echo "<< pipeline.git.tag >>" | sed 's/v//')
            export VERSION="$NUMBER.0.<< pipeline.number >>"
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker tag build:latest $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
            docker push $IMAGE_NAME:$VERSION
  build-helm-dev:
    executor: helm-builder
    steps:
      - checkout
      - run:
          name: Set version numbers in Helm
          command: |
            export CHART_VERSION="0.0.<< pipeline.number >>"
            export APP_VERSION="0.0.0.<< pipeline.number >>"
            sed "s/(chartVersion)/$CHART_VERSION/" "$CHART_PATH/Chart.yaml" > "$CHART_PATH/Chart.yaml"
            sed "s/(appVersion)/$APP_VERSION/" "$CHART_PATH/Chart.yaml" > "$CHART_PATH/Chart.yaml"
      - run:
          name: Package Helm chart
          command: |
            export CHART_VERSION="0.0.<< pipeline.number >>"
            helm package $CHART_PATH
      - run:
          name: Push Helm chart
          command: |
            export CHART_VERSION="0.0.<< pipeline.number >>"
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            helm push "$APP_NAME-$CHART_VERSION.tgz" "oci://$CHART_DEV_NAME"
  build-helm-release:
    executor: helm-builder
    steps:
      - checkout
      - run:
          name: Set version numbers in Helm
          command: |
            export NUMBER=$(echo "<< pipeline.git.tag >>" | sed 's/v//')
            export CHART_VERSION="$NUMBER.<< pipeline.number >>"
            export APP_VERSION="$NUMBER.0.<< pipeline.number >>"
            sed "s/(chartVersion)/$CHART_VERSION/" "$CHART_PATH/Chart.yaml" > "$CHART_PATH/Chart.yaml"
            sed "s/(appVersion)/$APP_VERSION/" "$CHART_PATH/Chart.yaml" > "$CHART_PATH/Chart.yaml"
      - run:
          name: Package Helm chart
          command: |
            export NUMBER=$(echo "<< pipeline.git.tag >>" | sed 's/v//')
            export CHART_VERSION="$NUMBER.<< pipeline.number >>"
            helm package $CHART_PATH
      - run:
          name: Push Helm chart
          command: |
            export NUMBER=$(echo "<< pipeline.git.tag >>" | sed 's/v//')
            export CHART_VERSION="$NUMBER.<< pipeline.number >>"
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            helm push "$APP_NAME-$CHART_VERSION.tgz" "oci://$CHART_NAME"

workflows:
  cicd:
    jobs:
      - build-docker-dev:
          filters:
            tags:
              ignore: /.*/
      - build-docker-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+$/
      - build-helm-dev:
          requires:
            - "build-docker-dev"
          filters:
            tags:
              ignore: /.*/
      - build-helm-release:
          requires:
            - "build-docker-release"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+$/