{{- if eq .Values.karmaChameleon.slack.existingSecretName "" }}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "karma-chameleon.fullname" . }}-slack"
  labels:
    {{- include "karma-chameleon.labels" . | nindent 4 }}
data:
  {{ .Values.karmaChameleon.slack.secretKeyAppToken | default "appToken" | nindent 2 }}: {{ required "Slack app token required" .Values.karmaChameleon.slack.appToken | b64enc | quote }}
  {{ .Values.karmaChameleon.slack.secretKeyBotToken | default "botToken" | nindent 2 }}: {{ required "Slack bot token required" .Values.karmaChameleon.slack.botToken | b64enc | quote }}
{{- end }}
