{{- if eq .Values.karmaChameleon.db.existingSecretName "" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karma-chameleon.fullname" . }}-db
  labels:
    {{- include "karma-chameleon.labels" . | nindent 4 }}
data:
  {{ .Values.karmaChameleon.db.secretKeyUsername | default "username" | nindent 2 }}: {{ required "Database username required" .Values.karmaChameleon.db.username | b64enc | quote }}
  {{ .Values.karmaChameleon.db.secretKeyPassword | default "password" | nindent 2 }}: {{ required "Database password required" .Values.karmaChameleon.db.password | b64enc | quote }}
{{- end }}
